### ISSUE TITLE
Decoding and encoding CSV is extremely slow

### ISSUE THREAD

**Issue by Hixie** [close2/csv#34]
This is only noticeable with large datasets but once you have anything resembling a non-trivial CSV file, this package takes absurd amounts of time to decode or encode the files.

**Comment by boukeversteegh** [comment]
I've done extensive file io testing with Dart and found that Dart's async transformers and raw IO bandwidth are actually a huge bottleneck. See https://github.com/dart-lang/sdk/issues/43534 .

The IO performance problem seems to be caused by many separate read operations, which have operating system overhead (on windows at least), and the fact that every async task is first scheduled and then executed at the next tick.

Sync operations can be twice as fast.

I haven't checked if this package can be used synchronously, but if you can I'd recommend:

- read your entire CSV file at once (dart has a limit of 1GB), or read it into chunks as large as possible
- process the data synchronously

**Comment by boukeversteegh** [comment]
Well, turns out my assumption was wrong. It indeed is slow. Please see PR #36 . This solves the encoding performance problem.
